server:
  port: 8085

spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://config-service:8888

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
