CREATE SCHEMA IF NOT EXISTS store;
CREATE SCHEMA IF NOT EXISTS courier;
CREATE SCHEMA IF NOT EXISTS location;
CREATE SCHEMA IF NOT EXISTS log;

INSERT INTO courier."COURIERS" ("CURRENT_X", "CURRENT_Y", "LAST_UPDATED", "NAME", "PHONE_NUMBER", "STATUS") VALUES (40.9923307, 29.1244229, '2025-05-25 23:30:42.000000', 'ALİ CEM DAS', '5548169938', true);

INSERT INTO store."STORES" ("ADDRESS", "DESCRIPTION", "NAME", "STATUS", "X_COORDINATE", "Y_COORDINATE") VALUES ('Ataşehir MMM Migros', 'Ataşehir MMM Migros', 'Ataşehir MMM Migros', true, 40.9923307, 29.1244229);
INSERT INTO store."STORES" ("ADDRESS", "DESCRIPTION", "NAME", "STATUS", "X_COORDINATE", "Y_COORDINATE") VALUES ('Novada MMM Migros', 'Novada MMM Migros', 'Novada MMM Migros', true, 40.986106, 29.1161293);
INSERT INTO store."STORES" ("ADDRESS", "DESCRIPTION", "NAME", "STATUS", "X_COORDINATE", "Y_COORDINATE") VALUES ('Beylikdüzü 5M Migros', 'Beylikdüzü 5M Migros', 'Beylikdüzü 5M Migros', true, 41.0066851, 28.6552262);
INSERT INTO store."STORES" ("ADDRESS", "DESCRIPTION", "NAME", "STATUS", "X_COORDINATE", "Y_COORDINATE") VALUES ('Ortaköy MMM Migros', 'Ortaköy MMM Migros', 'Ortaköy MMM Migros', true, 41.055783, 29.0210292);
INSERT INTO store."STORES" ("ADDRESS", "DESCRIPTION", "NAME", "STATUS", "X_COORDINATE", "Y_COORDINATE") VALUES ('Caddebostan MMM Migros', 'Caddebostan MMM Migros', 'Caddebostan MMM Migros', true, 40.9632463, 29.0630908);

COMMIT ;


