server:
  port: 8085

spring:
  application:
    name: auth-service
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  in
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

