spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: courier-service
          uri: lb://courier-service
          predicates:
            - Path=/api/couriers/**
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/api/stores/**
        - id: log-service
          uri: lb://log-service
          predicates:
            - Path=/api/logs/**
        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=/api/locations/** 