version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: migros-micro-db
    environment:
      POSTGRES_USER: acemdas
      POSTGRES_PASSWORD: migros
      POSTGRES_DB: migros-micro-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # init dosyaları için eklendi

volumes:
  postgres_data:
