spring:
  application:
    name: gateway-service
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      uri: http://localhost:8888
    discovery:
      enabled: true
    gateway:
      routes:
        - id: courier-service
          uri: lb://courier-service
          predicates:
            - Path=/api/couriers/**
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/api/stores/**
        - id: log-service
          uri: lb://log-service
          predicates:
            - Path=/api/logs/**
        - id: location-service
          uri: lb://location-service
          predicates:
            - Path=/api/courier-locations/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


