server:
  port: 8083

spring:
  application:
    name: log-service
  config:
    import: optional:configserver:http://localhost:8888
  elasticsearch:
    uris: http://localhost:9200

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
