server:
  port: 8082

spring:
  application:
    name: store-service
  config:
    import: optional:configserver:http://config-service:8888
  datasource:
    url: jdbc:postgresql://postgres-db:5432/migros-micro-db?currentSchema=store
    username: acemdas
    password: migros
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      fail-on-empty-beans: false
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
