server:
  port: 8084

spring:
  application:
    name: location-service
  config:
    import: optional:configserver:http://config-service:8888
  datasource:
    url: jdbc:postgresql://postgres-db:5432/migros-micro-db?currentSchema=location
    username: acemdas
    password: migros
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  zipkin:
    base-url: http://zipkin:9411
    enabled: true
    service:
      name: ${spring.application.name}

    tracing:
      sampling:
        probability: 1.0  # Tüm trafiği izle (0.0 ile 1.0 arasında değer alır)

  jackson:
    serialization:
      fail-on-empty-beans: false
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
management:
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
